// Ohio municipal income tax rates, for the city picker on the plan builder.
//
// Two sources, both read 08/31/2026:
//
//   The 416 RITA member municipalities, from the Regional Income Tax Agency's
//   own rate table at ritaohio.com/TaxRatesTable. JEDDs and JEDZs are left out
//   because nobody lives in one.
//
//   Seven Dayton-area cities that RITA does not collect for, each checked on
//   the city's own site:
//     Dayton 2.5%        daytonohio.gov, 2.25% plus 0.25% effective 01/01/2025
//     Kettering 2.25%    ketteringoh.org
//     Centerville 2.25%  centervilleohio.gov
//     Huber Heights 2.25% hhoh.org, effective 01/01/2015
//     Miamisburg 2.25%   cityofmiamisburg.com
//     Vandalia 2%        vandaliaohio.org
//     Beavercreek 0%     beavercreekohio.gov, "no municipal income tax"
//
// This is not every municipality in Ohio. Ohio has hundreds more that
// self-administer or collect through CCA, so a city missing from this list is
// not a city without a tax: the rate stays typeable by hand.
(function (global) {
  'use strict';

  const CITIES = [
    ["Aberdeen",1],
        ["Ada",1.65],
        ["Addyston",1.5],
        ["Adelphi",1],
        ["Alexandria",1],
        ["Alger",1],
        ["Amanda",1],
        ["Amsterdam",1],
        ["Andover",1.5],
        ["Antwerp",1],
        ["Apple Creek",1],
        ["Arcanum",1],
        ["Arlington Heights",2.1],
        ["Ashley",1],
        ["Ashville",1],
        ["Aurora",2],
        ["Avon",1.95],
        ["Avon Lake",1.5],
        ["Baltic",1.5],
        ["Baltimore",1],
        ["Barberton",2.25],
        ["Barnesville",1],
        ["Batavia",1],
        ["Bay Village",1.5],
        ["Beachwood",2],
        ["Beavercreek",0],
        ["Beaverdam",1],
        ["Bedford",3],
        ["Bedford Heights",2],
        ["Bellaire",1],
        ["Belle Center",1],
        ["Bellevue",2],
        ["Bellville",1],
        ["Belpre",1],
        ["Bentleyville",1],
        ["Berea",2],
        ["Bethel",1],
        ["Bettsville",1],
        ["Beverly",1.25],
        ["Bexley",2.5],
        ["Blanchester",1],
        ["Bloomdale",1],
        ["Bloomingdale",1],
        ["Bloomville",1],
        ["Boston Heights",2],
        ["Bowerston",1],
        ["Bradford",1],
        ["Bratenahl",2],
        ["Brecksville",2],
        ["Bremen",1],
        ["Brice",2],
        ["Bridgeport",1],
        ["Broadview Heights",2],
        ["Brooklyn",2.5],
        ["Brooklyn Heights",2.5],
        ["Bryan",1.8],
        ["Buckland",1],
        ["Burbank",1],
        ["Butler",1],
        ["Butler County Annexation",2],
        ["Cairo",0.5],
        ["Caldwell",1],
        ["Camden",1],
        ["Campbell",2.5],
        ["Canal Fulton",2],
        ["Canal Winchester",2],
        ["Cardington",1],
        ["Carroll",0.75],
        ["Carrollton",1],
        ["Catawba",1],
        ["Cecil",1],
        ["Cedarville",1.25],
        ["Centerburg",1],
        ["Centerville",2.25],
        ["Chagrin Falls",1.85],
        ["Chardon",2],
        ["Chesterville",1],
        ["Circleville",2.5],
        ["Clarksville",1],
        ["Cleveland Heights",2.25],
        ["Clinton",1],
        ["Coal Grove",1],
        ["College Corner",0],
        ["Columbiana",1],
        ["Commercial Point",0.75],
        ["Conesville",0.5],
        ["Continental",1],
        ["Corwin",0.5],
        ["Crestline",2],
        ["Creston",1],
        ["Crooksville",1.5],
        ["Cuyahoga Falls",2],
        ["Cuyahoga Heights",2.5],
        ["Danville",1.5],
        ["Darbyville",1],
        ["Dayton",2.5],
        ["DeGraff",1.75],
        ["Delta",1.5],
        ["Dennison",2],
        ["Doylestown",2],
        ["Dresden",1],
        ["Dunkirk",1],
        ["East Cleveland",2],
        ["East Palestine",1.5],
        ["Eastlake",2],
        ["Eaton",1.5],
        ["Edgerton",1.75],
        ["Edison",0.5],
        ["Elmore",1.75],
        ["Elmwood Place",2],
        ["Elyria",2.25],
        ["Empire",1],
        ["Euclid",2.85],
        ["Fairborn",2],
        ["Fairport Harbor",2],
        ["Fairview Park",2],
        ["Fayette",1.5],
        ["Fayetteville",1],
        ["Felicity",1],
        ["Forest",1.25],
        ["Fort Jennings",1],
        ["Fostoria",2],
        ["Frazeysburg",1],
        ["Fredericktown",1],
        ["Fremont",1.5],
        ["Fulton",1],
        ["Gahanna",2.5],
        ["Galena",1],
        ["Galion",2],
        ["Garfield Heights",2],
        ["Gates Mills",1],
        ["Genoa",1.5],
        ["Germantown",1.5],
        ["Gettysburg",1],
        ["Gibsonburg",1],
        ["Girard",2],
        ["Glenmont",1],
        ["Glenwillow",2],
        ["Golf Manor",1.7],
        ["Grafton",1.5],
        ["Grandview Heights",2.5],
        ["Gratis",1],
        ["Green Springs",1],
        ["Greenfield",1.625],
        ["Greenhills",1.5],
        ["Grove City",2],
        ["Groveport",2],
        ["Hamersville",1],
        ["Hamilton",2],
        ["Hanging Rock",1],
        ["Hanover",1],
        ["Harrisburg",1],
        ["Harrison",1],
        ["Harrod",1],
        ["Haskins",1],
        ["Helena",1],
        ["Highland Heights",2],
        ["Hilliard",2.5],
        ["Hiram",2.25],
        ["Holland",2.25],
        ["Holmesville",1],
        ["Hopedale",1],
        ["Huber Heights",2.25],
        ["Hudson",2],
        ["Hunting Valley",0],
        ["Huron",1],
        ["Independence",2],
        ["Jackson",1.5],
        ["Jackson Center",1.5],
        ["Jeffersonville",1],
        ["Jerry City",1],
        ["Jewett",1],
        ["Johnstown",1],
        ["Kent",2.25],
        ["Kettering",2.25],
        ["Killbuck",1],
        ["Kirkersville",1],
        ["Kirtland",2],
        ["LaGrange",1.5],
        ["Lakeline",1],
        ["Lakemore",2.25],
        ["Latty",1],
        ["Leesburg",1],
        ["Leetonia",1.5],
        ["Lewisburg",1.75],
        ["Liberty Center",1],
        ["Lincoln Heights",2],
        ["Lithopolis",1],
        ["Lockbourne",2.5],
        ["Lockington",1],
        ["Lockland",2.1],
        ["Lodi",1],
        ["Louisville",2],
        ["Loveland",1],
        ["Lowellville",2],
        ["Lyndhurst",2],
        ["Lyons",1],
        ["Macedonia",2.5],
        ["Madison Village",1],
        ["Maineville",1],
        ["Malinta",1],
        ["Malvern",1],
        ["Manchester",1],
        ["Mantua Village",2],
        ["Maple Heights",2.5],
        ["Marengo",1],
        ["Martins Ferry",1],
        ["Mayfield Heights",1.5],
        ["Mayfield Village",2],
        ["McClure",1],
        ["McDonald",2],
        ["Mechanicsburg",1],
        ["Medina",1.25],
        ["Melrose",1],
        ["Mentor",2],
        ["Metamora",1],
        ["Miamisburg",2.25],
        ["Middle Point",1.5],
        ["Middleburg Heights",2],
        ["Middleport",1],
        ["Midvale",1.5],
        ["Mifflin",1],
        ["Milan",1],
        ["Milford",1],
        ["Milford Center",1],
        ["Millbury",1.5],
        ["Miller City",1],
        ["Millersport",1],
        ["Millville",1],
        ["Mineral City",1],
        ["Minerva",1.5],
        ["Minerva Park",2],
        ["Mingo Junction",2],
        ["Mogadore",2.5],
        ["Monroeville",1],
        ["Montgomery",1],
        ["Moreland Hills",1],
        ["Morral",1],
        ["Moscow",0],
        ["Mount Eaton",1],
        ["Mount Sterling",1],
        ["Mount Victory",1],
        ["Mt Healthy",2],
        ["Napoleon",1.5],
        ["Nashville",1],
        ["Nelsonville",1.75],
        ["New Albany",2],
        ["New Bavaria",1],
        ["New Bloomington",1],
        ["New Boston",2.5],
        ["New Concord",2.25],
        ["New Franklin",2],
        ["New Lebanon",1],
        ["New Lexington",1],
        ["New Richmond",1],
        ["New Riegel",1],
        ["New Washington",1.5],
        ["New Waterford",1],
        ["Newburgh Heights",2],
        ["Newcomerstown",2],
        ["Newton Falls",1],
        ["Newtown",1],
        ["Ney",1],
        ["Niles",2],
        ["North Canton",2],
        ["North College Hill",1.5],
        ["North Hampton",1],
        ["North Lewisburg",1.75],
        ["North Olmsted",2],
        ["North Perry",1],
        ["North Ridgeville",1],
        ["North Robinson",1],
        ["North Royalton",2],
        ["Northfield Village",2],
        ["Northwood",1.5],
        ["Norton",2],
        ["Norwalk",1.5],
        ["Oak Harbor",1],
        ["Oak Hill",1],
        ["Oakwood",2.5],
        ["Oberlin",2.5],
        ["Octa",1],
        ["Olmsted Falls",1.5],
        ["Orange",2],
        ["Orrville",1],
        ["Ostrander",1],
        ["Ottawa",1],
        ["Ottawa Hills",1.5],
        ["Owensville",1],
        ["Oxford",2],
        ["Painesville",2],
        ["Parma Heights",3],
        ["Pataskala",1],
        ["Patterson",0.5],
        ["Payne",1],
        ["Pemberville",1],
        ["Peninsula",2],
        ["Pepper Pike",1],
        ["Perry",2],
        ["Piketon",1],
        ["Piqua",2],
        ["Pleasant Hill",1],
        ["Pleasantville",1],
        ["Pomeroy",1],
        ["Portage",1],
        ["Powell",2],
        ["Powhatan Point",1],
        ["Quincy",1],
        ["Ravenna",2.5],
        ["Reminderville",1.5],
        ["Reynoldsburg",2.5],
        ["Richmond Heights",2.25],
        ["Richwood",1],
        ["Ridgeway",1],
        ["Rio Grande",2],
        ["Ripley",1],
        ["Risingsun",1],
        ["Rittman",1.5],
        ["Rocky River",2],
        ["Rossford",2.25],
        ["Rushville",1],
        ["Rutland",1],
        ["Sabina",1.5],
        ["Saint Clairsville",0.75],
        ["Saint Paris",1],
        ["Salem",1.25],
        ["Salineville",1],
        ["Sandusky",1.25],
        ["Sardinia",1],
        ["Sebring",2],
        ["Seven Hills",2.5],
        ["Shaker Heights",2.25],
        ["Shawnee Hills",2],
        ["Sheffield Lake",2],
        ["Sheffield Village",2],
        ["Silver Lake",2],
        ["Silverton",1.25],
        ["Smithville",1.5],
        ["Solon",2],
        ["South Amherst",1],
        ["South Bloomfield",1],
        ["South Charleston",1.25],
        ["South Euclid",2],
        ["South Solon",1],
        ["South Vienna",1],
        ["Spencerville",1.5],
        ["Springdale",2],
        ["Springfield",2.4],
        ["St. Louisville",1],
        ["Steubenville",2],
        ["Stockport",1],
        ["Stone Creek",1],
        ["Stoutsville",1],
        ["Stratton",1],
        ["Streetsboro",2],
        ["Strongsville",2],
        ["Sugar Grove",0.75],
        ["Sugarcreek",1.5],
        ["Sunbury",1],
        ["Swanton",1.5],
        ["Sycamore",1],
        ["Tallmadge",2.25],
        ["Thurston",1],
        ["Timberlake",2],
        ["Tiro",1],
        ["Tontogany",1],
        ["Toronto",2],
        ["Tremont City",1],
        ["Trenton",1.5],
        ["Trimble",1],
        ["Tuscarawas",1.5],
        ["Twinsburg",2],
        ["Uhrichsville",2],
        ["Union City",1],
        ["University Heights",2.5],
        ["Upper Arlington",2.5],
        ["Urbana",1.4],
        ["Urbancrest",2],
        ["Utica",1.75],
        ["Valley View",2],
        ["Valleyview",0],
        ["Vandalia",2],
        ["Vermilion",1.5],
        ["Wadsworth",1.4],
        ["Wakeman",1],
        ["Walton Hills",2.5],
        ["Warrensville Heights",2.6],
        ["Warsaw",1],
        ["Washingtonville",1],
        ["Waterville",2],
        ["Wayne Lakes",1],
        ["Waynesfield",1],
        ["Waynesville",0.75],
        ["Wellington",1.75],
        ["Wellston",1],
        ["Wellsville",1.5],
        ["West Alexandria",1],
        ["West Elkton",1],
        ["West Lafayette",1.5],
        ["West Liberty",1],
        ["West Mansfield",1],
        ["West Salem",1],
        ["West Unity",1.5],
        ["Westlake",1.5],
        ["Weston",1],
        ["Whitehouse",1.5],
        ["Wickliffe",2],
        ["Williamsburg",1],
        ["Williamsport",0.5],
        ["Willoughby",2],
        ["Willoughby Hills",2],
        ["Willowick",2],
        ["Willshire",1],
        ["Windham",1.5],
        ["Wintersville",1],
        ["Woodlawn",2.3],
        ["Woodmere",2.5],
        ["Woodsfield",1],
        ["Woodstock",1],
        ["Worthington",2.5],
        ["Xenia",2.25],
        ["Yellow Springs",1.5],
        ["Youngstown",2.75]
  ].map(c => ({ name: c[0], rate: c[1] }));

  // The default rate, so the tool opens on something real rather than a guess.
  const average = CITIES.reduce((sum, c) => sum + c.rate, 0) / CITIES.length;

  function find(name) {
    const q = String(name || '').trim().toLowerCase();
    return CITIES.find(c => c.name.toLowerCase() === q) || null;
  }

  function search(query) {
    const q = String(query || '').trim().toLowerCase();
    if (!q) return CITIES;
    const starts = [], contains = [];
    CITIES.forEach(c => {
      const n = c.name.toLowerCase();
      if (n.startsWith(q)) starts.push(c);
      else if (n.includes(q)) contains.push(c);
    });
    return starts.concat(contains);
  }

  global.OhioCities = { CITIES, average, find, search };
})(typeof window !== 'undefined' ? window : globalThis);

if (typeof module !== 'undefined' && module.exports) module.exports = globalThis.OhioCities;
