// Ohio municipal income tax rates, for the city picker on the plan builder.
//
// Source: the Ohio Department of Taxation's own municipal rate table, the file
// behind The Finder, downloaded 08/31/2026 from
// thefinder.tax.ohio.gov (File Downloads, tax type Municipal,
// "Ohio Municipal Income Tax Rates", OHMuniRateTable.csv).
//
// That file carries an effective-date range per row; these are the rows in
// force on 08/31/2026. Where Ohio has more than one municipality of the same
// name the state qualifies it by county, which is kept as written: there are
// three Oakwoods and they do not share a rate.
//
// Beavercreek is the one hand-added row. It is absent from the state file
// because it levies no municipal income tax at all, confirmed on the city's
// own site (beavercreekohio.gov, "The City of Beavercreek presently has no
// municipal income tax"), and Dayton-area agents will look for it.
//
// Spot-checked against the cities' own sites on 08/31/2026: Dayton 2.5%,
// Kettering 2.25%, Centerville 2.25%, Huber Heights 2.25%, Miamisburg 2.25%,
// Vandalia 2%. All matched.
//
// Municipalities only. Ohio townships levy no income tax, so an agent living
// in an unincorporated township has no city rate to enter.
(function (global) {
  'use strict';

  const CITIES = [
    ["Aberdeen",1],
        ["Ada",1.65],
        ["Addyston",1.5],
        ["Adelphi",1],
        ["Akron",2.5],
        ["Alexandria",1],
        ["Alger",1],
        ["Alliance",2],
        ["Amanda",1],
        ["Amberley",2],
        ["Amelia",0],
        ["Amherst",1.5],
        ["Amsterdam",1],
        ["Andover",1.5],
        ["Anna",1.75],
        ["Ansonia",1],
        ["Antwerp",1],
        ["Apple Creek",1],
        ["Arcanum",1],
        ["Archbold",1.8],
        ["Arlington",1],
        ["Arlington Heights",2.1],
        ["Ashland",2],
        ["Ashley",1],
        ["Ashtabula",1.8],
        ["Ashville",1],
        ["Athens",1.95],
        ["Aurora",2],
        ["Avon",1.95],
        ["Avon Lake",1.5],
        ["Baltic",1.5],
        ["Baltimore",1],
        ["Barberton",2.25],
        ["Barnesville",1],
        ["Batavia",1],
        ["Bay Village",1.5],
        ["Beach City",1],
        ["Beachwood",2],
        ["Beavercreek",0],
        ["Beaverdam",1],
        ["Bedford",3],
        ["Bedford Heights",2],
        ["Bellaire",1],
        ["Belle Center",1],
        ["Bellefontaine",1.6],
        ["Bellevue",2],
        ["Bellville",1],
        ["Belpre",1],
        ["Bentleyville",1],
        ["Berea",2],
        ["Bethel",1],
        ["Bettsville",1],
        ["Beverly",1.25],
        ["Bexley",2.5],
        ["Blanchester",1],
        ["Bloomdale",1],
        ["Bloomingdale",1],
        ["Bloomville",1],
        ["Blue Ash",1.25],
        ["Bluffton",1.65],
        ["Bolivar",1],
        ["Boston Heights",2],
        ["Botkins",1.5],
        ["Bowerston",1],
        ["Bowling Green",2.15],
        ["Bradford",1],
        ["Bradner",1],
        ["Bratenahl",2],
        ["Brecksville",2],
        ["Bremen",1],
        ["Brewster",2],
        ["Brice",2],
        ["Bridgeport",1],
        ["Broadview Heights",2],
        ["Brook Park",2],
        ["Brooklyn",2.5],
        ["Brooklyn Heights",2.5],
        ["Brookville",2],
        ["Brunswick",2],
        ["Bryan",1.8],
        ["Buckland",1],
        ["Bucyrus",2.25],
        ["Burbank",1],
        ["Burton",1],
        ["Butler",1],
        ["Byesville",1],
        ["Cadiz",1],
        ["Cairo",0.5],
        ["Caldwell",1],
        ["Cambridge",2],
        ["Camden",1],
        ["Campbell",2.5],
        ["Canal Fulton",2],
        ["Canal Winchester",2],
        ["Canfield",1],
        ["Canton",2.5],
        ["Cardington",1],
        ["Carey",1.5],
        ["Carlisle",1.5],
        ["Carroll",0.75],
        ["Carrollton",1],
        ["Castine",0],
        ["Catawba",1],
        ["Cecil",1],
        ["Cedarville",1.25],
        ["Celina",1.5],
        ["Centerburg",1],
        ["Centerville",2.25],
        ["Chagrin Falls",1.85],
        ["Chardon",2],
        ["Chesterville",1],
        ["Cheviot",2],
        ["Chickasaw",1],
        ["Chillicothe",1.8],
        ["Cincinnati",1.8],
        ["Circleville",2.5],
        ["Clarksville",1],
        ["Clay Center",1.5],
        ["Clayton",2.5],
        ["Cleveland",2.5],
        ["Cleveland Heights",2.25],
        ["Clinton",1],
        ["Clyde",1.5],
        ["Coal Grove",1],
        ["Coldwater",1.5],
        ["College Corner",0],
        ["Columbiana",1],
        ["Columbus",2.5],
        ["Columbus Grove",1.25],
        ["Commercial Point",0.75],
        ["Conesville",0.5],
        ["Conneaut",1.65],
        ["Continental",1],
        ["Convoy",1],
        ["Corwin",0.5],
        ["Coshocton",2],
        ["Covington",1.5],
        ["Crestline",2],
        ["Creston",1],
        ["Cridersville",1.5],
        ["Crooksville",1.5],
        ["Cuyahoga Falls",2],
        ["Cuyahoga Heights",2.5],
        ["Cygnet",1],
        ["Dalton",1.5],
        ["Danville",1.5],
        ["Darbyville",1],
        ["Dayton",2.5],
        ["De Graff",1.75],
        ["Deer Park",1.5],
        ["Defiance",1.8],
        ["Delaware",1.85],
        ["Dellroy",0],
        ["Delphos",1.75],
        ["Delta",1.5],
        ["Dennison",2],
        ["Deshler",1],
        ["Dover",1.5],
        ["Doylestown",2],
        ["Dresden",1],
        ["Dublin",2],
        ["Dunkirk",1],
        ["East Canton",1.5],
        ["East Cleveland",2],
        ["East Liverpool",1.5],
        ["East Palestine",1.5],
        ["Eastlake",2],
        ["Eaton",1.5],
        ["Edgerton",1.75],
        ["Edison",0.5],
        ["Edon",1.75],
        ["Elida",0.75],
        ["Elmore",1.75],
        ["Elmwood Place",2],
        ["Elyria",2.25],
        ["Empire",1],
        ["Englewood",1.75],
        ["Euclid",2.85],
        ["Evendale",1.2],
        ["Fairborn",2],
        ["Fairfax",1.75],
        ["Fairfield",1.5],
        ["Fairlawn",2],
        ["Fairport Harbor",2],
        ["Fairview Park",2],
        ["Farmersville",1],
        ["Fayette",1.5],
        ["Fayetteville",1],
        ["Felicity",1],
        ["Findlay",1],
        ["Forest",1.25],
        ["Forest Park",1.5],
        ["Fort Jennings",1],
        ["Fort Loramie",1.5],
        ["Fort Recovery",1.5],
        ["Fostoria",2],
        ["Franklin",2],
        ["Frazeysburg",1],
        ["Fredericksburg",1],
        ["Fredericktown",1],
        ["Fremont",1.5],
        ["Fulton",1],
        ["Gahanna",2.5],
        ["Galena",1],
        ["Galion",2],
        ["Gallipolis",1.5],
        ["Gambier",1.5],
        ["Garfield Heights",2],
        ["Garrettsville",1.75],
        ["Gates Mills",1],
        ["Geneva",1.5],
        ["Geneva-on-the-Lake",1.5],
        ["Genoa",1.5],
        ["Georgetown",1],
        ["Gettysburg",1],
        ["Gibsonburg",1],
        ["Girard",2],
        ["Glandorf",1.5],
        ["Glenmont",1],
        ["Glenwillow",2],
        ["Gnadenhutten",1.5],
        ["Golf Manor",1.7],
        ["Grafton",1.5],
        ["Grand Rapids",1],
        ["Grand River",2],
        ["Grandview Heights",2.5],
        ["Granville",1.5],
        ["Gratis",1],
        ["Green",2],
        ["Green Springs",1],
        ["Greenfield",1.625],
        ["Greenhills",1.5],
        ["Greenville",1.5],
        ["Greenwich",1],
        ["Grove City",2],
        ["Groveport",2],
        ["Hamersville",1],
        ["Hamilton",2],
        ["Hamler",1],
        ["Hanging Rock",1],
        ["Hanover",1],
        ["Harrisburg",1],
        ["Harrison",1],
        ["Harrod",1],
        ["Hartville",1.5],
        ["Haskins",1],
        ["Heath",2],
        ["Hebron",1.5],
        ["Helena",1],
        ["Hicksville",1],
        ["Highland Heights",2],
        ["Highland Hills",2.5],
        ["Hilliard",2.5],
        ["Hillsboro",1.5],
        ["Hiram",2.25],
        ["Holgate",1],
        ["Holland",2.25],
        ["Holmesville",1],
        ["Hopedale",1],
        ["Hubbard",1.5],
        ["Huber Heights",2.25],
        ["Hudson",2],
        ["Hunting Valley",0],
        ["Huntsville",1],
        ["Huron",1],
        ["Independence",2],
        ["Indian Hill",0.45],
        ["Ironton",1],
        ["Jackson",1.5],
        ["Jackson Center",1.5],
        ["Jamestown",1],
        ["Jefferson",1.5],
        ["Jeffersonville",1],
        ["Jenera",1],
        ["Jerry City",1],
        ["Jewett",1],
        ["Johnstown",1],
        ["Kalida",1],
        ["Kent",2.25],
        ["Kenton",1.5],
        ["Kettering",2.25],
        ["Kettlersville",0],
        ["Killbuck",1],
        ["Kirby",1],
        ["Kirkersville",1],
        ["Kirtland",2],
        ["Lagrange",1.5],
        ["Lakeline",1],
        ["Lakemore",2.25],
        ["Lakeview",1],
        ["Lakewood",1.5],
        ["Lancaster",2.3],
        ["Latty",1],
        ["Lebanon",1.5],
        ["Leesburg",1],
        ["Leetonia",1.5],
        ["Leipsic",1.5],
        ["Lewisburg",1.75],
        ["Lexington",1],
        ["Liberty Center",1],
        ["Lima",1.5],
        ["Lincoln Heights",2],
        ["Linndale",2],
        ["Lisbon",2],
        ["Lithopolis",1],
        ["Lockbourne",2.5],
        ["Lockington",1],
        ["Lockland",2.1],
        ["Lodi",1],
        ["Logan",2],
        ["London",1.5],
        ["Lorain",2.5],
        ["Lordstown",1.5],
        ["Loudonville",1.75],
        ["Louisville",2],
        ["Loveland",1],
        ["Lowellville",2],
        ["Luckey",1],
        ["Lyndhurst",2],
        ["Lyons",1],
        ["Macedonia",2.5],
        ["Madeira",1],
        ["Madison",1],
        ["Maineville",1],
        ["Malinta",1],
        ["Malta",1],
        ["Malvern",1],
        ["Manchester",1],
        ["Mansfield",2.25],
        ["Mantua",2],
        ["Maple Heights",2.5],
        ["Marble Cliff",2],
        ["Marengo",1],
        ["Mariemont",1.25],
        ["Marietta",1.85],
        ["Marion",2],
        ["Marshallville",1],
        ["Martins Ferry",1],
        ["Marysville",1.5],
        ["Mason",1.12],
        ["Massillon",2],
        ["Maumee",1.5],
        ["Mayfield",2],
        ["Mayfield Heights",1.5],
        ["Mcclure",1],
        ["Mccomb",1],
        ["Mcconnelsville",1],
        ["Mcdonald",2],
        ["Mcguffey",1],
        ["Mechanicsburg",1],
        ["Medina",1.25],
        ["Melrose",1],
        ["Mendon",0],
        ["Mentor",2],
        ["Mentor-on-the-Lake",2],
        ["Metamora",1],
        ["Miamisburg",2.25],
        ["Middle Point",1.5],
        ["Middleburg Heights",2],
        ["Middlefield",1.25],
        ["Middleport",1],
        ["Middletown",2],
        ["Midvale",1.5],
        ["Mifflin",1],
        ["Milan",1],
        ["Milford",1],
        ["Milford Center",1],
        ["Millbury",1.5],
        ["Miller City",1],
        ["Millersburg",1.5],
        ["Millersport",1],
        ["Millville",1],
        ["Mineral City",1],
        ["Minerva",1.5],
        ["Minerva Park",2],
        ["Mingo Junction",2],
        ["Minster",1.5],
        ["Mogadore",2.5],
        ["Monroe",2],
        ["Monroeville",1],
        ["Montgomery",1],
        ["Montpelier",1.8],
        ["Moraine",2.5],
        ["Moreland Hills",1],
        ["Morral",1],
        ["Morrow",1],
        ["Moscow",0],
        ["Mount Blanchard",1],
        ["Mount Cory",1],
        ["Mount Eaton",1],
        ["Mount Gilead",1.25],
        ["Mount Healthy",2],
        ["Mount Orab",1.35],
        ["Mount Sterling",1],
        ["Mount Vernon",2],
        ["Mount Victory",1],
        ["Munroe Falls",2.25],
        ["Napoleon",1.5],
        ["Nashville",1],
        ["Navarre",1.75],
        ["Nelsonville",1.75],
        ["New Albany",2],
        ["New Bavaria",1],
        ["New Bloomington",1],
        ["New Boston",2.5],
        ["New Bremen",1.5],
        ["New Carlisle",1.5],
        ["New Concord",2.25],
        ["New Franklin",2],
        ["New Knoxville",1.5],
        ["New Lebanon",1],
        ["New Lexington",1],
        ["New London",1.5],
        ["New Madison",1],
        ["New Miami",1.75],
        ["New Paris",1],
        ["New Philadelphia",1.5],
        ["New Richmond",1],
        ["New Riegel",1],
        ["New Washington",1.5],
        ["New Waterford",1],
        ["Newark",1.75],
        ["Newburgh Heights",2],
        ["Newcomerstown",2],
        ["Newton Falls",1],
        ["Newtonsville",0],
        ["Newtown",1],
        ["Ney",1],
        ["Niles",2],
        ["North Baltimore",1],
        ["North Canton",2],
        ["North College Hill",1.5],
        ["North Kingsville",1.3],
        ["North Lewisburg",1.75],
        ["North Olmsted",2],
        ["North Perry",1],
        ["North Randall",2.75],
        ["North Ridgeville",1],
        ["North Robinson",1],
        ["North Royalton",2],
        ["North Star",0.5],
        ["Northfield",2],
        ["Northwood",1.5],
        ["Norton",2],
        ["Norwalk",1.5],
        ["Norwood",2],
        ["Oak Harbor",1],
        ["Oak Hill",1],
        ["Oakwood (Cuyahoga)",2.5],
        ["Oakwood (Montgomery)",2.5],
        ["Oakwood (Paulding)",1],
        ["Oberlin",2.5],
        ["Obetz",2.5],
        ["Octa",1],
        ["Ohio City",1],
        ["Olmsted Falls",1.5],
        ["Ontario",1.5],
        ["Orange",2],
        ["Oregon",2.25],
        ["Orrville",1],
        ["Orwell",1.5],
        ["Osgood",1],
        ["Ostrander",1],
        ["Ottawa",1],
        ["Ottawa Hills",1.5],
        ["Ottoville",1],
        ["Owensville",1],
        ["Oxford",2],
        ["Painesville",2],
        ["Pandora",1.5],
        ["Parma",2.5],
        ["Parma Heights",3],
        ["Pataskala",1],
        ["Patterson",0.5],
        ["Paulding",1],
        ["Payne",1],
        ["Pemberville",1],
        ["Peninsula",2],
        ["Pepper Pike",1],
        ["Perry",2],
        ["Perrysburg",1.5],
        ["Perrysville",1],
        ["Phillipsburg",1.5],
        ["Pickerington",1],
        ["Piketon",1],
        ["Pioneer",1],
        ["Piqua",2],
        ["Pitsburg",1],
        ["Plain City",1.5],
        ["Pleasant Hill",1],
        ["Pleasantville",1],
        ["Plymouth",1],
        ["Pomeroy",1],
        ["Port Clinton",1.5],
        ["Port Washington",1.5],
        ["Portage",1],
        ["Portsmouth",2.5],
        ["Powell",2],
        ["Powhatan Point",1],
        ["Quincy",1],
        ["Ravenna",2.5],
        ["Reading",2],
        ["Reminderville",1.5],
        ["Reynoldsburg",2.5],
        ["Richfield",2],
        ["Richmond Heights",2.25],
        ["Richwood",1],
        ["Ridgeway",1],
        ["Rio Grande",2],
        ["Ripley",1],
        ["Risingsun",1],
        ["Rittman",1.5],
        ["Riverside",2.5],
        ["Rock Creek",1],
        ["Rockford",1],
        ["Rocky River",2],
        ["Roseville",1],
        ["Rossford",2.25],
        ["Roswell",1],
        ["Rushsylvania",1],
        ["Rushville",1],
        ["Russells Point",1],
        ["Russia",1.5],
        ["Rutland",1],
        ["Sabina",1.5],
        ["Salem",1.25],
        ["Salineville",1],
        ["Sandusky",1.25],
        ["Sardinia",1],
        ["Scio",1],
        ["Sebring",2],
        ["Seven Hills",2.5],
        ["Seville",1],
        ["Shaker Heights",2.25],
        ["Sharonville",1.5],
        ["Sheffield",2],
        ["Sheffield Lake",2],
        ["Shelby",1.75],
        ["Sherrodsville",1],
        ["Sherwood",1],
        ["Shreve",1],
        ["Sidney",1.75],
        ["Silver Lake",2],
        ["Silverton",1.25],
        ["Smithfield",0],
        ["Smithville",1.5],
        ["Solon",2],
        ["Somerset",1],
        ["South Amherst",1],
        ["South Bloomfield",1],
        ["South Charleston",1.25],
        ["South Euclid",2],
        ["South Lebanon",1],
        ["South Russell",1.25],
        ["South Solon",1],
        ["South Vienna",1],
        ["South Zanesville",1.5],
        ["Spencerville",1.5],
        ["Springboro",1.5],
        ["Springdale",2],
        ["Springfield",2.4],
        ["St. Bernard",2.1],
        ["St. Clairsville",0.75],
        ["St. Henry",1.5],
        ["St. Louisville",1],
        ["St. Marys",1.5],
        ["St. Paris",1],
        ["Steubenville",2],
        ["Stone Creek",1],
        ["Stoutsville",1],
        ["Stow",2],
        ["Strasburg",1.5],
        ["Stratton",1],
        ["Streetsboro",2],
        ["Strongsville",2],
        ["Struthers",2],
        ["Stryker",1.5],
        ["Sugar Grove",0.75],
        ["Sugarcreek",1.5],
        ["Sunbury",1],
        ["Swanton",1.5],
        ["Sycamore",1],
        ["Sylvania",1.5],
        ["Tallmadge",2.25],
        ["Thurston",1],
        ["Tiffin",2],
        ["Timberlake",2],
        ["Tipp City",1.5],
        ["Tiro",1],
        ["Toledo",2.5],
        ["Tontogany",1],
        ["Toronto",2],
        ["Tremont City",1],
        ["Trenton",1.5],
        ["Trimble",1],
        ["Trotwood",2.75],
        ["Troy",1.75],
        ["Tuscarawas",1.5],
        ["Twinsburg",2],
        ["Uhrichsville",2],
        ["Union",1.5],
        ["Union City",1],
        ["University Heights",2.5],
        ["Upper Arlington",2.5],
        ["Upper Sandusky",1.75],
        ["Urbana",1.4],
        ["Urbancrest",2],
        ["Utica",1.75],
        ["Valley Hi",1],
        ["Valley View",2],
        ["Van Wert",1.72],
        ["Vandalia",2],
        ["Vanlue",1],
        ["Vermilion",1.5],
        ["Versailles",1.5],
        ["Wadsworth",1.4],
        ["Wakeman",1],
        ["Walbridge",1.5],
        ["Walton Hills",2.5],
        ["Wapakoneta",1.5],
        ["Warren",2.5],
        ["Warrensville Heights",2.6],
        ["Warsaw",1],
        ["Washington",1.95],
        ["Washingtonville",1],
        ["Waterville",2],
        ["Wauseon",1.5],
        ["Waverly City",1],
        ["Wayne",0.75],
        ["Wayne Lakes",1],
        ["Waynesfield",1],
        ["Waynesville",0.75],
        ["Wellington",1.75],
        ["Wellston",1],
        ["Wellsville",1.5],
        ["West Alexandria",1],
        ["West Carrollton City",2.25],
        ["West Elkton",1],
        ["West Jefferson",1],
        ["West Lafayette",1.5],
        ["West Liberty",1],
        ["West Mansfield",1],
        ["West Millgrove",1],
        ["West Milton",1.5],
        ["West Salem",1],
        ["West Union",1],
        ["West Unity",1.5],
        ["Westerville",2],
        ["Westfield Center",1],
        ["Westlake",1.5],
        ["Weston",1],
        ["Whitehall",2.5],
        ["Whitehouse",1.5],
        ["Wickliffe",2],
        ["Willard",1.75],
        ["Williamsburg",1],
        ["Williamsport",0.5],
        ["Willoughby",2],
        ["Willoughby Hills",2],
        ["Willowick",2],
        ["Willshire",1],
        ["Wilmington",1.5],
        ["Wilmot",1.75],
        ["Windham",1.5],
        ["Wintersville",1],
        ["Woodlawn",2.3],
        ["Woodmere",2.5],
        ["Woodsfield",1],
        ["Woodstock",1],
        ["Wooster",1.5],
        ["Worthington",2.5],
        ["Wyoming",1],
        ["Xenia",2.25],
        ["Yellow Springs",1.5],
        ["Yorkshire",1],
        ["Youngstown",2.75],
        ["Zanesville",1.9]
  ].map(c => ({ name: c[0], rate: c[1] }));

  // The default rate, so the tool opens on something real rather than a guess.
  const average = CITIES.reduce((sum, c) => sum + c.rate, 0) / CITIES.length;

  function find(name) {
    const q = String(name || '').trim().toLowerCase();
    return CITIES.find(c => c.name.toLowerCase() === q) || null;
  }

  function search(query) {
    const q = String(query || '').trim().toLowerCase();
    if (!q) return CITIES;
    const starts = [], contains = [];
    CITIES.forEach(c => {
      const n = c.name.toLowerCase();
      if (n.startsWith(q)) starts.push(c);
      else if (n.includes(q)) contains.push(c);
    });
    return starts.concat(contains);
  }

  global.OhioCities = { CITIES, average, find, search };
})(typeof window !== 'undefined' ? window : globalThis);

if (typeof module !== 'undefined' && module.exports) module.exports = globalThis.OhioCities;
